// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SudokuPages.Data.Migrations
{
    [DbContext(typeof(SudokuDbContext))]
    [Migration("20250102035708_InitialDb")]
    partial class InitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Puzzle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<decimal?>("Difficulty")
                        .HasColumnType("TEXT")
                        .HasColumnName("Difficulty");

                    b.Property<string>("Initial")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Initial");

                    b.Property<string>("Solution")
                        .HasColumnType("TEXT")
                        .HasColumnName("Solution");

                    b.HasKey("Id");

                    b.HasIndex("Initial")
                        .IsUnique();

                    b.ToTable("Puzzles", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
